#!/bin/bash
#Run a test case to make sure the built program runs
#Copy the contents of the TESTCASE to the build directory and run this script

mkdir Experiment
cd Experiment
mkdir VTP
mkdir ParticleData
cd ..

./CCC ./PhysParamData.csv ./Experiment
